WebApplication3/ViewModels/ForgotPassword.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication3.ViewModels
{
    public class ForgotPassword
    {
        [Required(ErrorMessage = "Please enter your email ")]
        [DataType(DataType.EmailAddress)]
        [RegularExpression(@"^[\w-\.]+@([\w-]+\.)+[\w-]{2,}$", ErrorMessage = "Please enter a valid email.")]
        public string Email { get; set; }
    }
}

WebApplication3/ViewModels/Login.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication3.ViewModels
{
	public class Login
	{
		[Required(ErrorMessage = "Please enter your email ")]
		[DataType(DataType.EmailAddress)]
		[RegularExpression(@"^[\w-\.]+@([\w-]+\.)+[\w-]{2,}$", ErrorMessage = "Please enter a valid email.")]
		public string Email { get; set; }
		[Required(ErrorMessage = "Please enter your password ")]
		[DataType(DataType.Password)]
		[RegularExpression(@"^[^<>]*$")]
		public string Password { get; set; }
		public bool RememberMe { get; set; }
	}
}

WebApplication3/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace WebApplication3.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

WebApplication3/Pages/ForgotPassword.cshtml.cs
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Net.Mail;
using System.Net.Mime;
using System.Net;
using System.Text;
using WebApplication3.Model;
using WebApplication3.ViewModels;

namespace WebApplication3.Pages
{
    public class ForgotPasswordModel : PageModel
    {
        [BindProperty]
        public ForgotPassword FPModel { get; set; }

        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager;

        public ForgotPasswordModel(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
        }
        public void OnGet()
        {
        }
        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var dataProtectionProvider = DataProtectionProvider.Create("EncryptData");
                var protector = dataProtectionProvider.CreateProtector("MySecretKey");

                var currentUser = await userManager.FindByEmailAsync(FPModel.Email);
                if (currentUser != null)
                {
                    var ProtectedEmail = protector.Protect(FPModel.Email);
                    var token = await userManager.GeneratePasswordResetTokenAsync(currentUser);
                    var ProtectedToken = protector.Protect(token);

                    var smtpClient = new SmtpClient("smtp.ethereal.email")
                    {
                        Port = 587,
                        Credentials = new NetworkCredential("rose.swift@ethereal.email", "UN1wPX1jXm2Vw1bEGe"),
                        EnableSsl = true,
                    };

                    var attachment = Attachment.CreateAttachmentFromString(System.Text.Json.JsonSerializer.Serialize(new
                    {
                        Message = "Hello World!"
                    }), "helloworld.json", Encoding.UTF8, MediaTypeNames.Application.Json);

                    var message = new MailMessage("fromtest@test.com", "sendertest@test.com")
                    {
                        Subject = "Reset password email",
                        Body = $"<p>Click on this link to verify your account <a href=https://localhost:7175/ResetPassword?email={ProtectedEmail}&token={ProtectedToken} target=\"_blank\">https://localhost:7175/ResetPassword?email={ProtectedEmail}&token={ProtectedToken}</a></p>",
                        IsBodyHtml = true,
                    };

                    message.Attachments.Add(attachment);

                    try
                    {
                        smtpClient.Send(message);
                        TempData["SuccessMessage"] = "Password reset email sent successfully.";
                    }
                    catch (SmtpException ex)
                    {
                        TempData["ErrorMessage"] = $"Failed to send Password reset email: {ex.Message}";
                        Console.WriteLine(ex.ToString());
                    }

                    TempData["Message"] = "A Password reset email was sent to you.";
                    return RedirectToPage("");
                }
                else
                {
                    TempData["ErrorMessage"] = "Email address not found.";
                    return RedirectToPage();
                }
            }
            return Page();
        }
    }
}

WebApplication3/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Net.Mail;
using System.Net.Mime;
using System.Net;
using System.Text;
using WebApplication3.Model;
using System.Text.Json;

namespace WebApplication3.Pages
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly IHttpContextAccessor contxt;
        private readonly SignInManager<ApplicationUser> signInManager;



        public IndexModel(ILogger<IndexModel> logger, IHttpContextAccessor httpContextAccessor, SignInManager<ApplicationUser> signInManager)
        {
            _logger = logger;
            contxt = httpContextAccessor;
            this.signInManager = signInManager;
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostLogoutAsync()
        {
            await signInManager.SignOutAsync();
            contxt.HttpContext.Session.Clear();

            if (Request.Cookies.ContainsKey("ASP.NET_SessionId"))
            {
                Response.Cookies.Delete("ASP.NET_SessionId");
            }

            if (Request.Cookies.ContainsKey("AuthToken"))
            {
                Response.Cookies.Delete("AuthToken");
            }

            return RedirectToPage("Login");
        }

    }
}

WebApplication3/Pages/Login.cshtml.cs
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Net;
using WebApplication3.Model;
using WebApplication3.ViewModels;
using System.Text.Encodings.Web;

namespace WebApplication3.Pages
{
    public class LoginModel : PageModel
    {
        [BindProperty]
        public Login LModel { get; set; }

        private readonly SignInManager<ApplicationUser> signInManager;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IHttpContextAccessor contxt;

        public LoginModel(SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager, IHttpContextAccessor contxt)
        {
            this.signInManager = signInManager;
            this.userManager = userManager; // Inject UserManager
            this.contxt = contxt;
        }

        public void OnGet()
        {
        }


        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var dataProtectionProvider = DataProtectionProvider.Create("EncryptData");
                var protector = dataProtectionProvider.CreateProtector("MySecretKey");

                var result = await signInManager.PasswordSignInAsync(LModel.Email, LModel.Password,
                    LModel.RememberMe, true);
                var currentUser = await userManager.FindByEmailAsync(LModel.Email);
                if (result.Succeeded && currentUser != null && currentUser.EmailConfirmed == true)
                {
                    currentUser.LastLogin = DateTime.Now;
                    await userManager.UpdateAsync(currentUser);
                    contxt.HttpContext.Session.SetString("LoggedIn", "True");
                    contxt.HttpContext.Session.SetString("Email", protector.Protect(LModel.Email));
                    contxt.HttpContext.Session.SetString("Password", protector.Protect(LModel.Password));
                    contxt.HttpContext.Session.SetString("Full Name", currentUser.FullName.ToString());
                    contxt.HttpContext.Session.SetString("Credit Card", currentUser.CreditCard.ToString());
                    contxt.HttpContext.Session.SetString("Gender", currentUser.Gender.ToString());
                    contxt.HttpContext.Session.SetString("Mobile Number", currentUser.MobileNo.ToString());
                    contxt.HttpContext.Session.SetString("Delivery Address", currentUser.DeliveryAddress.ToString());
                    contxt.HttpContext.Session.SetString("About Me", currentUser.AboutMe.ToString());
                    contxt.HttpContext.Session.SetString("Photo Path", currentUser.PhotoPath.ToString());
                    contxt.HttpContext.Session.SetString("Last Login", currentUser.LastLogin.ToString());
                    contxt.HttpContext.Session.SetString("Previous Passwords", currentUser.PreviousPasswords.ToString());
					contxt.HttpContext.Session.SetString("Last Password Change", currentUser.LastPasswordChange.ToString());
					string authToken = Guid.NewGuid().ToString();

                    contxt.HttpContext.Session.SetString("AuthToken", authToken);

                    contxt.HttpContext.Response.Cookies.Append("AuthToken", authToken, new CookieOptions
                    {
                        HttpOnly = true,
                        Secure = true,
                        Expires = DateTimeOffset.UtcNow.AddDays(3)
                    });
                    return RedirectToPage("Index");
                }
                else if(currentUser == null)
                {
                    TempData["ErrorMessage"] = "Unable to retrieve user information.";
                    return RedirectToPage();
                }
                else if (result.IsLockedOut)
                {
                    TempData["ErrorMessage"] = "Account is locked out due to 3 failed login attempts. Please try again in later.";
                    return RedirectToPage();
                }
                else if (currentUser.EmailConfirmed != true)
                {
                    TempData["ErrorMessage"] = "Your account is not activated, please check your email for an activation link.";
                    return RedirectToPage();
                }
                else
                {
                    TempData["ErrorMessage"] = "Incorrect email or password. Please try again.";
                    return RedirectToPage();
                }
            }
            return Page();
        }
    }
}

WebApplication3/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebApplication3.Model;

namespace WebApplication3.Pages
{
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<ApplicationUser> signInManager;
        private readonly IHttpContextAccessor contxt;

        public LogoutModel(SignInManager<ApplicationUser> signInManager, IHttpContextAccessor contxt)
        {
            this.signInManager = signInManager;
            this.contxt = contxt;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            if (string.IsNullOrEmpty(contxt.HttpContext.Session.GetString("LoggedIn")) &&
                string.IsNullOrEmpty(contxt.HttpContext.Session.GetString("AuthToken")))
            {
                await ClearSessionAsync();
                return RedirectToPage("Index");
            }
            else
            {
                return Page();
            }
        }

        public async Task<IActionResult> OnPostLogoutAsync()
        {
            await signInManager.SignOutAsync();
            await ClearSessionAsync();
            return RedirectToPage("Index");
        }

        public IActionResult OnPostDontLogoutAsync()
        {
            return RedirectToPage("Index");
        }

        private async Task ClearSessionAsync()
        {
            contxt.HttpContext.Session.Clear();

            if (Request.Cookies.ContainsKey("ASP.NET_SessionId"))
            {
                Response.Cookies.Delete("ASP.NET_SessionId");
            }

            if (Request.Cookies.ContainsKey("AuthToken"))
            {
                Response.Cookies.Delete("AuthToken");
            }
        }
    }
}

WebApplication3/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebApplication3.Pages
{
    [Authorize(Roles = "User")]
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

WebApplication3/Pages/ResetPassword.cshtml.cs
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NanoidDotNet;
using Newtonsoft.Json;
using static WebApplication3.Pages.RegisterModel;
using System.Text.Encodings.Web;
using WebApplication3.Model;
using WebApplication3.ViewModels;

namespace WebApplication3.Pages
{
    public class ResetPasswordModel : PageModel
    {

        [BindProperty]
        public ResetPassword RPModel { get; set; }

        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager;

        public ResetPasswordModel(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
        }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync(string EmailAccount, string ResetToken)

        {
            {
                var dataProtectionProvider = DataProtectionProvider.Create("EncryptData");
                var protector = dataProtectionProvider.CreateProtector("MySecretKey");

                var UnprotectedEmail = protector.Unprotect(EmailAccount);

                var UnprotectedToken = protector.Unprotect(ResetToken);

                var user = await userManager.FindByEmailAsync(UnprotectedEmail);

                var previousPasswordsArray = user.PreviousPasswords?.Split('|');
                if (user != null)
                {
                    if (RPModel.Password != protector.Unprotect(previousPasswordsArray[0]) && RPModel.Password != protector.Unprotect(previousPasswordsArray[1]))
                    {

                        var result = await userManager.ResetPasswordAsync(user, UnprotectedToken, RPModel.Password);

                        var NewPreviousPasswords = $"{protector.Protect(RPModel.Password)}|{previousPasswordsArray[0]}";

                        user.PreviousPasswords = NewPreviousPasswords;

                        user.LastPasswordChange = DateTime.Now;

                        await userManager.UpdateAsync(user);

                        if (result.Succeeded)
                        {
                            TempData["SuccessMessage"] = "Password was successfully reset.";
                            return RedirectToPage("Login");
                        }

                        else
                        {
                            foreach (var error in result.Errors)
                            {
                                ModelState.AddModelError("", error.Description);
                            }
                        }
                    }
                    else
                    {
                        TempData["ErrorMessage"] = "Password cannot be the same as previous 2 passwords.";
                        return RedirectToPage("/ResetPassword", new { email = EmailAccount });
                    }
                }
                else
                {
                    TempData["ErrorMessage"] = "User not found.";
                    return RedirectToPage("/ResetPassword", new { email = EmailAccount });
                }
            }
            return Page();
        }
    }
}

WebApplication3/Pages/ForgotPassword.cshtml
@page
@using WebApplication3.Model;
@model WebApplication3.Pages.ForgotPasswordModel
@{
}

<div class="container mt-5">

    <div class="row justify-content-center align-items-center">

        <div class="col-sm-12 col-md-12 col-lg-4">
            <h1 class="mb-3">Forgot Password? </h1>

            <form method="post">
                <h3>Enter the email linked to your account.</h3>
                @if (TempData["ErrorMessage"] != null)
                {
                    <div class="alert alert-danger" role="alert">
                        @TempData["ErrorMessage"]
                    </div>
                }
                <div class="mb-3">
                    <label class="form-label" asp-for="FPModel.Email">Email Address</label>
                    <input id="emailInput" type="Text" asp-for="FPModel.Email" class="form-control" />
                    <span asp-validaton-for="FPModel.Email" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <button id="verifyButton" type="submit" class="btn btn-primary">Verify</button>
                </div>
            </form>
        </div>
    </div>
</div>

WebApplication3/Pages/Index.cshtml
@page
@model IndexModel
@using Microsoft.AspNetCore.Identity
@using WebApplication3.Model
@using Microsoft.AspNetCore.DataProtection;
@using Microsoft.AspNetCore.Antiforgery
@inject IAntiforgery Antiforgery
@inject IHttpContextAccessor contxt;
@inject SignInManager<ApplicationUser> SignInManager
@{
    ViewData["Title"] = "Home page";
    var dataProtectionProvider = DataProtectionProvider.Create("EncryptData");
    var protector = dataProtectionProvider.CreateProtector("MySecretKey");
    var PreviousPasswords = contxt.HttpContext.Session.GetString("Previous Passwords");
    var previousPasswordsArray = PreviousPasswords?.Split('|');
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    @{
        if (SignInManager.IsSignedIn(User) && 
        contxt.HttpContext.Session.GetString("LoggedIn") == "True" && 
        contxt.HttpContext.Session.GetString("AuthToken") != null && 
        Request.Cookies["AuthToken"] != null)
        {
            string authTokenFromCookie = Request.Cookies["AuthToken"];
            string authTokenFromSession = contxt.HttpContext.Session.GetString("AuthToken");

            if (authTokenFromCookie == authTokenFromSession)
            {
                <div id="UserInformation" disabled>
                    <p>Your Email: @protector.Unprotect(contxt.HttpContext.Session.GetString("Email"))</p>
                    <p>Your Password: @protector.Unprotect(contxt.HttpContext.Session.GetString("Password"))</p>
                    <p>Your Full Name: @protector.Unprotect(contxt.HttpContext.Session.GetString("Full Name"))</p>
                    <p>Your credit card: @protector.Unprotect(contxt.HttpContext.Session.GetString("Credit Card"))</p>
                    <p>Your gender: @protector.Unprotect(contxt.HttpContext.Session.GetString("Gender"))</p>
                    <p>Your mobile number: @protector.Unprotect(contxt.HttpContext.Session.GetString("Mobile Number"))</p>
                    <p>Your delivery address: @protector.Unprotect(contxt.HttpContext.Session.GetString("Delivery Address"))</p>
                    <p>Your about me: @protector.Unprotect(contxt.HttpContext.Session.GetString("About Me"))</p>
                    <p>Your last login: @contxt.HttpContext.Session.GetString("Last Login")</p>
                    @if (@protector.Unprotect(previousPasswordsArray[1]) != ""){
                        <p>Your previous passwords: @protector.Unprotect(previousPasswordsArray[0]).ToString() & @protector.Unprotect(previousPasswordsArray[1]).ToString()</p>
                    }
                    else
                    {
                        <p>Your previous passwords: @protector.Unprotect(previousPasswordsArray[0]).ToString()</p>
                    }
                    <p>Your last password change: @contxt.HttpContext.Session.GetString("Last Password Change")</p>
                    <p>Your photo:</p>
                    <img src="@contxt.HttpContext.Session.GetString("Photo Path")" alt="User Photo" />
                </div>
            }
        }
        else if (SignInManager.IsSignedIn(User) && contxt.HttpContext.Session.GetString("LoggedIn") == null)
        {
            <p>Your session timed out, <a asp-page-handler="Logout">please sign in again.</a></p>
        }
        else{
            <p>You are not logged in.</p>
        }
    }
</div>

<script type="text/javascript">
    document.addEventListener("DOMContentLoaded", function () {
        var UserDetails = document.getElementById("UserInformation");

        function checkTokenValidity() {
            var token = @Antiforgery.GetAndStoreTokens(HttpContext).RequestToken;

            var isValidToken = (token !== '');

            if (isValidToken) {
                UserDetails.disabled = false;
            } else {
                UserDetails.disabled = true;
            }
        }

        checkTokenValidity();
    });
</script>

WebApplication3/Pages/Login.cshtml
@page
@model WebApplication3.Pages.LoginModel
@{
	<div class="container mt-5">

		<div class="row justify-content-center align-items-center">

			<div class="col-sm-12 col-md-12 col-lg-4">
				<h1 class="mb-3">Login </h1>

				<form method="post">
					@if (TempData["ErrorMessage"] != null)
					{
						<div class="alert alert-danger" role="alert">
							@TempData["ErrorMessage"]
						</div>
					}
					@if (TempData["SuccessMessage"] != null)
					{
						<div class="alert alert-success" role="alert">
							@TempData["SuccessMessage"]
						</div>
					}
					<div class="mb-3">
						<label class="form-label" asp-for="LModel.Email">Email Address</label>
						<input type="Text" asp-for="LModel.Email" class="form-control" />
						<span asp-validaton-for="LModel.Email" class="text-danger"></span>
					</div>

					<div class="mb-3">
						<label class="form-label" asp-for="LModel.Password">Password</label>
						<input type="password" asp-for="LModel.Password" class="form-control" />
						<span asp-validaton-for="LModel.Password" class="text-danger"></span>
					</div>

					<div class="mb-3 form-check">
						<input type="checkbox" asp-for="LModel.RememberMe" class="form-check-input" />
						<label class="form-check-label" asp-for="LModel.RememberMe">Remember Me?</label>
					</div>

					<div class="mb-3">
						<a class="text-dark" asp-area="" asp-page="/ForgotPassword">Forgot password?</a>
					</div>

					<div class="mb-3">
						<button type="submit" class="btn btn-primary">Login</button>
					</div>
				</form>
			</div>
		</div>
	</div>
}

WebApplication3/Pages/Logout.cshtml
@page
@using Microsoft.AspNetCore.Identity
@using WebApplication3.Model
@inject IHttpContextAccessor contxt;
@inject SignInManager<ApplicationUser> SignInManager
@model WebApplication3.Pages.LogoutModel
@{ 
	if (SignInManager.IsSignedIn(User) &&
		contxt.HttpContext.Session.GetString("LoggedIn") != "" &&
		contxt.HttpContext.Session.GetString("AuthToken") != null)
	{
	<form method="post">
		<div class="container mt-5">
			<div class="row justify-content-center">
				<div class="col-sm-12 col-md-12 col-lg-4">
					<p> Are you sure you want to logout? </p>
					<p>
						<button class="btn btn-primary" asp-page-handler="Logout">Yes</button>
						<button class="btn btn-light ml-5 border-dark" asp-page-handler="DontLogout">No</button>
					</p>
				</div>
			</div>
		</div>
		</form>
	}
	else
	{
		await Model.OnGetAsync();
	}
}

WebApplication3/Pages/Register.cshtml
@page
@model WebApplication3.Pages.RegisterModel
@{

}

<div class="container mt-5">
    <div class="row justify-content-center align-items-center">
        <div class="col-sm-12 col-md-12 col-lg-4">
            <h1 class="mb-3">Register</h1>
            <form method="post" enctype="multipart/form-data" id="register-form">
                @if (TempData["ErrorMessage"] != null)
                {
                    <div class="alert alert-danger" role="alert">
                        @TempData["ErrorMessage"]
                    </div>
                }
                <div asp-validation-summary="All" class="text-danger"></div>

                <div class="mb-3">
                    <label class="form-label" asp-for="RModel.FullName">Full Name</label>
                    <input type="text" asp-for="RModel.FullName" class="form-control" />
                    <span asp-validation-for="RModel.FullName" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="RModel.CreditCard">Credit Card</label>
                    <input type="number" asp-for="RModel.CreditCard" class="form-control" maxlength="16"/>
                    <span asp-validation-for="RModel.CreditCard" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="RModel.Gender">Gender</label>
                    <select asp-for="RModel.Gender" class="form-control">
                        <option value="Male">Male</option>
                        <option value="Female">Female</option>
                    </select>
                    <span asp-validation-for="RModel.Gender" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="RModel.MobileNo">Mobile Number</label>
                    <input type="number" asp-for="RModel.MobileNo" class="form-control" />
                    <span asp-validation-for="RModel.MobileNo" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="RModel.DeliveryAddress">Delivery Address</label>
                    <input type="text" asp-for="RModel.DeliveryAddress" class="form-control" />
                    <span asp-validation-for="RModel.DeliveryAddress" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="RModel.Email">Email Address</label>
                    <input type="email" asp-for="RModel.Email" class="form-control" />
                    <span asp-validation-for="RModel.Email" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="RModel.Password">Password</label>
                    <input type="password" id="password" asp-for="RModel.Password" class="form-control" onkeyup="javascript:PasswordChecker()"/>
                    <span asp-validation-for="RModel.Password" class="text-danger"></span>
                </div>
                <p id="PasswordText"></p>

                <div class="mb-3">
                    <label class="form-label" asp-for="RModel.ConfirmPassword">Confirm Password</label>
                    <input type="password" id="confirmPassword" asp-for="RModel.ConfirmPassword" class="form-control" onkeyup="ConfirmPasswordChecker()" />
                    <span asp-validation-for="RModel.ConfirmPassword" class="text-danger"></span>
                </div>
                <p id="ConfirmPasswordText"></p>

                <div class="mb-3">
                    <label class="form-label" asp-for="RModel.Photo">Photo (JPEG only)</label>
                    <input type="file" accept="image/jpeg" asp-for="RModel.Photo" class="form-control" />
                    <span asp-validation-for="RModel.Photo" class="text-danger"></span>
                </div>

                <div class="mb-3">
                    <label class="form-label" asp-for="RModel.AboutMe">About Me</label>
                    <input type="text" asp-for="RModel.AboutMe" class="form-control" />
                    <span asp-validation-for="RModel.AboutMe" class="text-danger"></span>
                </div>

                <input type="hidden" id="recaptchaToken" name="recaptchaToken" />

                <div class="mb-3">
                    <button class="btn btn-primary"
                            type="submit">
                        Register
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    function PasswordChecker() {
        var password = document.getElementById("password").value;
        var passwordText = document.getElementById("PasswordText");

        if (password.length < 12) {
            passwordText.innerText = "Password must consist of at least 12 characters";
            passwordText.style.color = "Red"
        }
        else if (!/[\d]/.test(password)) {
            passwordText.innerText = "Password must consist of at one number";
            passwordText.style.color = "Red"
        }
        else if (!/[a-z]/.test(password)) {
            passwordText.innerText = "Password must consist of at least one lowercase letter";
            passwordText.style.color = "Red"
        }
        else if (!/[A-Z]/.test(password)) {
            passwordText.innerText = "Password must consist of at least one uppercase letter";
            passwordText.style.color = "Red"
        }
        else if (!/[\W]/.test(password)) {
            passwordText.innerText = "Password must consist of at least one special character";
            passwordText.style.color = "Red"
        }
        else {
            passwordText.innerText = ""
        }

    }

    function ConfirmPasswordChecker() {
        var password = document.getElementById("password").value;
        var confirmPassword = document.getElementById("confirmPassword").value;
        var confirmPasswordText = document.getElementById("ConfirmPasswordText");

        if (confirmPassword != password) {
            confirmPasswordText.innerText = "Passwords do not match"
            confirmPasswordText.style.color = "Red"
        }
        else {
            confirmPasswordText.innerText = ""
        }
    }
</script>
<script src="https://www.google.com/recaptcha/api.js?render=6LfD614pAAAAANHzMS7s5HYfo7GsLHwxvszNbZPz"></script>
<script>
    var recaptchaResponse = 0;
    grecaptcha.ready(function () {
        grecaptcha.execute('6LfD614pAAAAANHzMS7s5HYfo7GsLHwxvszNbZPz', { action: 'submit' })
            .then(function (token) {
                recaptchaResponse = document.getElementById('recaptchaToken');
                recaptchaResponse.value = token;
            });
    });
</script>